// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.aixohub.portfolio.model.proto.v1;

public interface PClientOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aixohub.portfolio.PClient)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>repeated .com.aixohub.portfolio.PSecurity securities = 2;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PSecurity> 
      getSecuritiesList();
  /**
   * <code>repeated .com.aixohub.portfolio.PSecurity securities = 2;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PSecurity getSecurities(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PSecurity securities = 2;</code>
   */
  int getSecuritiesCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PSecurity securities = 2;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PSecurityOrBuilder> 
      getSecuritiesOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PSecurity securities = 2;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PSecurityOrBuilder getSecuritiesOrBuilder(
      int index);

  /**
   * <code>repeated .com.aixohub.portfolio.PAccount accounts = 3;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PAccount> 
      getAccountsList();
  /**
   * <code>repeated .com.aixohub.portfolio.PAccount accounts = 3;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PAccount getAccounts(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PAccount accounts = 3;</code>
   */
  int getAccountsCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PAccount accounts = 3;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PAccountOrBuilder> 
      getAccountsOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PAccount accounts = 3;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PAccountOrBuilder getAccountsOrBuilder(
      int index);

  /**
   * <code>repeated .com.aixohub.portfolio.PPortfolio portfolios = 4;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PPortfolio> 
      getPortfoliosList();
  /**
   * <code>repeated .com.aixohub.portfolio.PPortfolio portfolios = 4;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PPortfolio getPortfolios(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PPortfolio portfolios = 4;</code>
   */
  int getPortfoliosCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PPortfolio portfolios = 4;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PPortfolioOrBuilder> 
      getPortfoliosOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PPortfolio portfolios = 4;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PPortfolioOrBuilder getPortfoliosOrBuilder(
      int index);

  /**
   * <code>repeated .com.aixohub.portfolio.PTransaction transactions = 5;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PTransaction> 
      getTransactionsList();
  /**
   * <code>repeated .com.aixohub.portfolio.PTransaction transactions = 5;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PTransaction getTransactions(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PTransaction transactions = 5;</code>
   */
  int getTransactionsCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PTransaction transactions = 5;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PTransactionOrBuilder> 
      getTransactionsOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PTransaction transactions = 5;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PTransactionOrBuilder getTransactionsOrBuilder(
      int index);

  /**
   * <code>repeated .com.aixohub.portfolio.PInvestmentPlan plans = 6;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PInvestmentPlan> 
      getPlansList();
  /**
   * <code>repeated .com.aixohub.portfolio.PInvestmentPlan plans = 6;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PInvestmentPlan getPlans(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PInvestmentPlan plans = 6;</code>
   */
  int getPlansCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PInvestmentPlan plans = 6;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PInvestmentPlanOrBuilder> 
      getPlansOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PInvestmentPlan plans = 6;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PInvestmentPlanOrBuilder getPlansOrBuilder(
      int index);

  /**
   * <code>repeated .com.aixohub.portfolio.PWatchlist watchlists = 7;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PWatchlist> 
      getWatchlistsList();
  /**
   * <code>repeated .com.aixohub.portfolio.PWatchlist watchlists = 7;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PWatchlist getWatchlists(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PWatchlist watchlists = 7;</code>
   */
  int getWatchlistsCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PWatchlist watchlists = 7;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PWatchlistOrBuilder> 
      getWatchlistsOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PWatchlist watchlists = 7;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PWatchlistOrBuilder getWatchlistsOrBuilder(
      int index);

  /**
   * <code>repeated .com.aixohub.portfolio.PTaxonomy taxonomies = 8;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PTaxonomy> 
      getTaxonomiesList();
  /**
   * <code>repeated .com.aixohub.portfolio.PTaxonomy taxonomies = 8;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PTaxonomy getTaxonomies(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PTaxonomy taxonomies = 8;</code>
   */
  int getTaxonomiesCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PTaxonomy taxonomies = 8;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PTaxonomyOrBuilder> 
      getTaxonomiesOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PTaxonomy taxonomies = 8;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PTaxonomyOrBuilder getTaxonomiesOrBuilder(
      int index);

  /**
   * <code>repeated .com.aixohub.portfolio.PDashboard dashboards = 9;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PDashboard> 
      getDashboardsList();
  /**
   * <code>repeated .com.aixohub.portfolio.PDashboard dashboards = 9;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PDashboard getDashboards(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PDashboard dashboards = 9;</code>
   */
  int getDashboardsCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PDashboard dashboards = 9;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PDashboardOrBuilder> 
      getDashboardsOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PDashboard dashboards = 9;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PDashboardOrBuilder getDashboardsOrBuilder(
      int index);

  /**
   * <code>map&lt;string, string&gt; properties = 10;</code>
   */
  int getPropertiesCount();
  /**
   * <code>map&lt;string, string&gt; properties = 10;</code>
   */
  boolean containsProperties(
      java.lang.String key);
  /**
   * Use {@link #getPropertiesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getProperties();
  /**
   * <code>map&lt;string, string&gt; properties = 10;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getPropertiesMap();
  /**
   * <code>map&lt;string, string&gt; properties = 10;</code>
   */
  /* nullable */
java.lang.String getPropertiesOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; properties = 10;</code>
   */
  java.lang.String getPropertiesOrThrow(
      java.lang.String key);

  /**
   * <code>.com.aixohub.portfolio.PSettings settings = 11;</code>
   * @return Whether the settings field is set.
   */
  boolean hasSettings();
  /**
   * <code>.com.aixohub.portfolio.PSettings settings = 11;</code>
   * @return The settings.
   */
  com.aixohub.portfolio.model.proto.v1.PSettings getSettings();
  /**
   * <code>.com.aixohub.portfolio.PSettings settings = 11;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PSettingsOrBuilder getSettingsOrBuilder();

  /**
   * <code>string baseCurrency = 12;</code>
   * @return The baseCurrency.
   */
  java.lang.String getBaseCurrency();
  /**
   * <code>string baseCurrency = 12;</code>
   * @return The bytes for baseCurrency.
   */
  com.google.protobuf.ByteString
      getBaseCurrencyBytes();
}
