// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.aixohub.portfolio.model.proto.v1;

public interface PECBDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aixohub.portfolio.PECBData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 lastModified = 1;</code>
   * @return The lastModified.
   */
  long getLastModified();

  /**
   * <code>repeated .com.aixohub.portfolio.PExchangeRateTimeSeries series = 2;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PExchangeRateTimeSeries> 
      getSeriesList();
  /**
   * <code>repeated .com.aixohub.portfolio.PExchangeRateTimeSeries series = 2;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PExchangeRateTimeSeries getSeries(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PExchangeRateTimeSeries series = 2;</code>
   */
  int getSeriesCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PExchangeRateTimeSeries series = 2;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PExchangeRateTimeSeriesOrBuilder> 
      getSeriesOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PExchangeRateTimeSeries series = 2;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PExchangeRateTimeSeriesOrBuilder getSeriesOrBuilder(
      int index);
}
