// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.aixohub.portfolio.model.proto.v1;

public interface PExchangeRateTimeSeriesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aixohub.portfolio.PExchangeRateTimeSeries)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string baseCurrency = 1;</code>
   * @return The baseCurrency.
   */
  java.lang.String getBaseCurrency();
  /**
   * <code>string baseCurrency = 1;</code>
   * @return The bytes for baseCurrency.
   */
  com.google.protobuf.ByteString
      getBaseCurrencyBytes();

  /**
   * <code>string termCurrency = 2;</code>
   * @return The termCurrency.
   */
  java.lang.String getTermCurrency();
  /**
   * <code>string termCurrency = 2;</code>
   * @return The bytes for termCurrency.
   */
  com.google.protobuf.ByteString
      getTermCurrencyBytes();

  /**
   * <code>repeated .com.aixohub.portfolio.PExchangeRate exchangeRates = 3;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PExchangeRate> 
      getExchangeRatesList();
  /**
   * <code>repeated .com.aixohub.portfolio.PExchangeRate exchangeRates = 3;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PExchangeRate getExchangeRates(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PExchangeRate exchangeRates = 3;</code>
   */
  int getExchangeRatesCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PExchangeRate exchangeRates = 3;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PExchangeRateOrBuilder> 
      getExchangeRatesOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PExchangeRate exchangeRates = 3;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PExchangeRateOrBuilder getExchangeRatesOrBuilder(
      int index);
}
