// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.aixohub.portfolio.model.proto.v1;

public interface PKeyValueOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aixohub.portfolio.PKeyValue)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string key = 1;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 1;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>.com.aixohub.portfolio.PAnyValue value = 2;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>.com.aixohub.portfolio.PAnyValue value = 2;</code>
   * @return The value.
   */
  com.aixohub.portfolio.model.proto.v1.PAnyValue getValue();
  /**
   * <code>.com.aixohub.portfolio.PAnyValue value = 2;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PAnyValueOrBuilder getValueOrBuilder();
}
