// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.aixohub.portfolio.model.proto.v1;

public interface PMapOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aixohub.portfolio.PMap)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.aixohub.portfolio.PKeyValue entries = 1;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PKeyValue> 
      getEntriesList();
  /**
   * <code>repeated .com.aixohub.portfolio.PKeyValue entries = 1;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PKeyValue getEntries(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PKeyValue entries = 1;</code>
   */
  int getEntriesCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PKeyValue entries = 1;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PKeyValueOrBuilder> 
      getEntriesOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PKeyValue entries = 1;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PKeyValueOrBuilder getEntriesOrBuilder(
      int index);
}
