// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.aixohub.portfolio.model.proto.v1;

public interface PSecurityEventOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aixohub.portfolio.PSecurityEvent)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.aixohub.portfolio.PSecurityEvent.Type type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.com.aixohub.portfolio.PSecurityEvent.Type type = 1;</code>
   * @return The type.
   */
  com.aixohub.portfolio.model.proto.v1.PSecurityEvent.Type getType();

  /**
   * <pre>
   * epoch day
   * </pre>
   *
   * <code>int64 date = 2;</code>
   * @return The date.
   */
  long getDate();

  /**
   * <code>string details = 3;</code>
   * @return The details.
   */
  java.lang.String getDetails();
  /**
   * <code>string details = 3;</code>
   * @return The bytes for details.
   */
  com.google.protobuf.ByteString
      getDetailsBytes();

  /**
   * <code>repeated .com.aixohub.portfolio.PAnyValue data = 4;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PAnyValue> 
      getDataList();
  /**
   * <code>repeated .com.aixohub.portfolio.PAnyValue data = 4;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PAnyValue getData(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PAnyValue data = 4;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PAnyValue data = 4;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PAnyValueOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PAnyValue data = 4;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PAnyValueOrBuilder getDataOrBuilder(
      int index);

  /**
   * <code>string source = 5;</code>
   * @return The source.
   */
  java.lang.String getSource();
  /**
   * <code>string source = 5;</code>
   * @return The bytes for source.
   */
  com.google.protobuf.ByteString
      getSourceBytes();
}
