// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.aixohub.portfolio.model.proto.v1;

/**
 * Protobuf type {@code com.aixohub.portfolio.PSettings}
 */
public final class PSettings extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.aixohub.portfolio.PSettings)
    PSettingsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PSettings.newBuilder() to construct.
  private PSettings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PSettings() {
    bookmarks_ = java.util.Collections.emptyList();
    attributeTypes_ = java.util.Collections.emptyList();
    configurationSets_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PSettings();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.aixohub.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PSettings_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.aixohub.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PSettings_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.aixohub.portfolio.model.proto.v1.PSettings.class, com.aixohub.portfolio.model.proto.v1.PSettings.Builder.class);
  }

  public static final int BOOKMARKS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.aixohub.portfolio.model.proto.v1.PBookmark> bookmarks_;
  /**
   * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.aixohub.portfolio.model.proto.v1.PBookmark> getBookmarksList() {
    return bookmarks_;
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PBookmarkOrBuilder> 
      getBookmarksOrBuilderList() {
    return bookmarks_;
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
   */
  @java.lang.Override
  public int getBookmarksCount() {
    return bookmarks_.size();
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
   */
  @java.lang.Override
  public com.aixohub.portfolio.model.proto.v1.PBookmark getBookmarks(int index) {
    return bookmarks_.get(index);
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
   */
  @java.lang.Override
  public com.aixohub.portfolio.model.proto.v1.PBookmarkOrBuilder getBookmarksOrBuilder(
      int index) {
    return bookmarks_.get(index);
  }

  public static final int ATTRIBUTETYPES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<com.aixohub.portfolio.model.proto.v1.PAttributeType> attributeTypes_;
  /**
   * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
   */
  @java.lang.Override
  public java.util.List<com.aixohub.portfolio.model.proto.v1.PAttributeType> getAttributeTypesList() {
    return attributeTypes_;
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PAttributeTypeOrBuilder> 
      getAttributeTypesOrBuilderList() {
    return attributeTypes_;
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
   */
  @java.lang.Override
  public int getAttributeTypesCount() {
    return attributeTypes_.size();
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
   */
  @java.lang.Override
  public com.aixohub.portfolio.model.proto.v1.PAttributeType getAttributeTypes(int index) {
    return attributeTypes_.get(index);
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
   */
  @java.lang.Override
  public com.aixohub.portfolio.model.proto.v1.PAttributeTypeOrBuilder getAttributeTypesOrBuilder(
      int index) {
    return attributeTypes_.get(index);
  }

  public static final int CONFIGURATIONSETS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.aixohub.portfolio.model.proto.v1.PConfigurationSet> configurationSets_;
  /**
   * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
   */
  @java.lang.Override
  public java.util.List<com.aixohub.portfolio.model.proto.v1.PConfigurationSet> getConfigurationSetsList() {
    return configurationSets_;
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PConfigurationSetOrBuilder> 
      getConfigurationSetsOrBuilderList() {
    return configurationSets_;
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
   */
  @java.lang.Override
  public int getConfigurationSetsCount() {
    return configurationSets_.size();
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
   */
  @java.lang.Override
  public com.aixohub.portfolio.model.proto.v1.PConfigurationSet getConfigurationSets(int index) {
    return configurationSets_.get(index);
  }
  /**
   * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
   */
  @java.lang.Override
  public com.aixohub.portfolio.model.proto.v1.PConfigurationSetOrBuilder getConfigurationSetsOrBuilder(
      int index) {
    return configurationSets_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < bookmarks_.size(); i++) {
      output.writeMessage(1, bookmarks_.get(i));
    }
    for (int i = 0; i < attributeTypes_.size(); i++) {
      output.writeMessage(2, attributeTypes_.get(i));
    }
    for (int i = 0; i < configurationSets_.size(); i++) {
      output.writeMessage(3, configurationSets_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < bookmarks_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, bookmarks_.get(i));
    }
    for (int i = 0; i < attributeTypes_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, attributeTypes_.get(i));
    }
    for (int i = 0; i < configurationSets_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, configurationSets_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.aixohub.portfolio.model.proto.v1.PSettings)) {
      return super.equals(obj);
    }
    com.aixohub.portfolio.model.proto.v1.PSettings other = (com.aixohub.portfolio.model.proto.v1.PSettings) obj;

    if (!getBookmarksList()
        .equals(other.getBookmarksList())) return false;
    if (!getAttributeTypesList()
        .equals(other.getAttributeTypesList())) return false;
    if (!getConfigurationSetsList()
        .equals(other.getConfigurationSetsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBookmarksCount() > 0) {
      hash = (37 * hash) + BOOKMARKS_FIELD_NUMBER;
      hash = (53 * hash) + getBookmarksList().hashCode();
    }
    if (getAttributeTypesCount() > 0) {
      hash = (37 * hash) + ATTRIBUTETYPES_FIELD_NUMBER;
      hash = (53 * hash) + getAttributeTypesList().hashCode();
    }
    if (getConfigurationSetsCount() > 0) {
      hash = (37 * hash) + CONFIGURATIONSETS_FIELD_NUMBER;
      hash = (53 * hash) + getConfigurationSetsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.aixohub.portfolio.model.proto.v1.PSettings parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aixohub.portfolio.model.proto.v1.PSettings parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aixohub.portfolio.model.proto.v1.PSettings parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aixohub.portfolio.model.proto.v1.PSettings parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aixohub.portfolio.model.proto.v1.PSettings parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.aixohub.portfolio.model.proto.v1.PSettings parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.aixohub.portfolio.model.proto.v1.PSettings parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aixohub.portfolio.model.proto.v1.PSettings parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aixohub.portfolio.model.proto.v1.PSettings parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.aixohub.portfolio.model.proto.v1.PSettings parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.aixohub.portfolio.model.proto.v1.PSettings parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.aixohub.portfolio.model.proto.v1.PSettings parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.aixohub.portfolio.model.proto.v1.PSettings prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.aixohub.portfolio.PSettings}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.aixohub.portfolio.PSettings)
      com.aixohub.portfolio.model.proto.v1.PSettingsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.aixohub.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PSettings_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.aixohub.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.aixohub.portfolio.model.proto.v1.PSettings.class, com.aixohub.portfolio.model.proto.v1.PSettings.Builder.class);
    }

    // Construct using com.aixohub.portfolio.model.proto.v1.PSettings.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (bookmarksBuilder_ == null) {
        bookmarks_ = java.util.Collections.emptyList();
      } else {
        bookmarks_ = null;
        bookmarksBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      if (attributeTypesBuilder_ == null) {
        attributeTypes_ = java.util.Collections.emptyList();
      } else {
        attributeTypes_ = null;
        attributeTypesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (configurationSetsBuilder_ == null) {
        configurationSets_ = java.util.Collections.emptyList();
      } else {
        configurationSets_ = null;
        configurationSetsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.aixohub.portfolio.model.proto.v1.ClientProtos.internal_static_name_abuchen_portfolio_PSettings_descriptor;
    }

    @java.lang.Override
    public com.aixohub.portfolio.model.proto.v1.PSettings getDefaultInstanceForType() {
      return com.aixohub.portfolio.model.proto.v1.PSettings.getDefaultInstance();
    }

    @java.lang.Override
    public com.aixohub.portfolio.model.proto.v1.PSettings build() {
      com.aixohub.portfolio.model.proto.v1.PSettings result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.aixohub.portfolio.model.proto.v1.PSettings buildPartial() {
      com.aixohub.portfolio.model.proto.v1.PSettings result = new com.aixohub.portfolio.model.proto.v1.PSettings(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.aixohub.portfolio.model.proto.v1.PSettings result) {
      if (bookmarksBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          bookmarks_ = java.util.Collections.unmodifiableList(bookmarks_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.bookmarks_ = bookmarks_;
      } else {
        result.bookmarks_ = bookmarksBuilder_.build();
      }
      if (attributeTypesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          attributeTypes_ = java.util.Collections.unmodifiableList(attributeTypes_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.attributeTypes_ = attributeTypes_;
      } else {
        result.attributeTypes_ = attributeTypesBuilder_.build();
      }
      if (configurationSetsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          configurationSets_ = java.util.Collections.unmodifiableList(configurationSets_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.configurationSets_ = configurationSets_;
      } else {
        result.configurationSets_ = configurationSetsBuilder_.build();
      }
    }

    private void buildPartial0(com.aixohub.portfolio.model.proto.v1.PSettings result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.aixohub.portfolio.model.proto.v1.PSettings) {
        return mergeFrom((com.aixohub.portfolio.model.proto.v1.PSettings)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.aixohub.portfolio.model.proto.v1.PSettings other) {
      if (other == com.aixohub.portfolio.model.proto.v1.PSettings.getDefaultInstance()) return this;
      if (bookmarksBuilder_ == null) {
        if (!other.bookmarks_.isEmpty()) {
          if (bookmarks_.isEmpty()) {
            bookmarks_ = other.bookmarks_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBookmarksIsMutable();
            bookmarks_.addAll(other.bookmarks_);
          }
          onChanged();
        }
      } else {
        if (!other.bookmarks_.isEmpty()) {
          if (bookmarksBuilder_.isEmpty()) {
            bookmarksBuilder_.dispose();
            bookmarksBuilder_ = null;
            bookmarks_ = other.bookmarks_;
            bitField0_ = (bitField0_ & ~0x00000001);
            bookmarksBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBookmarksFieldBuilder() : null;
          } else {
            bookmarksBuilder_.addAllMessages(other.bookmarks_);
          }
        }
      }
      if (attributeTypesBuilder_ == null) {
        if (!other.attributeTypes_.isEmpty()) {
          if (attributeTypes_.isEmpty()) {
            attributeTypes_ = other.attributeTypes_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureAttributeTypesIsMutable();
            attributeTypes_.addAll(other.attributeTypes_);
          }
          onChanged();
        }
      } else {
        if (!other.attributeTypes_.isEmpty()) {
          if (attributeTypesBuilder_.isEmpty()) {
            attributeTypesBuilder_.dispose();
            attributeTypesBuilder_ = null;
            attributeTypes_ = other.attributeTypes_;
            bitField0_ = (bitField0_ & ~0x00000002);
            attributeTypesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getAttributeTypesFieldBuilder() : null;
          } else {
            attributeTypesBuilder_.addAllMessages(other.attributeTypes_);
          }
        }
      }
      if (configurationSetsBuilder_ == null) {
        if (!other.configurationSets_.isEmpty()) {
          if (configurationSets_.isEmpty()) {
            configurationSets_ = other.configurationSets_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureConfigurationSetsIsMutable();
            configurationSets_.addAll(other.configurationSets_);
          }
          onChanged();
        }
      } else {
        if (!other.configurationSets_.isEmpty()) {
          if (configurationSetsBuilder_.isEmpty()) {
            configurationSetsBuilder_.dispose();
            configurationSetsBuilder_ = null;
            configurationSets_ = other.configurationSets_;
            bitField0_ = (bitField0_ & ~0x00000004);
            configurationSetsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getConfigurationSetsFieldBuilder() : null;
          } else {
            configurationSetsBuilder_.addAllMessages(other.configurationSets_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.aixohub.portfolio.model.proto.v1.PBookmark m =
                  input.readMessage(
                      com.aixohub.portfolio.model.proto.v1.PBookmark.parser(),
                      extensionRegistry);
              if (bookmarksBuilder_ == null) {
                ensureBookmarksIsMutable();
                bookmarks_.add(m);
              } else {
                bookmarksBuilder_.addMessage(m);
              }
              break;
            } // case 10
            case 18: {
              com.aixohub.portfolio.model.proto.v1.PAttributeType m =
                  input.readMessage(
                      com.aixohub.portfolio.model.proto.v1.PAttributeType.parser(),
                      extensionRegistry);
              if (attributeTypesBuilder_ == null) {
                ensureAttributeTypesIsMutable();
                attributeTypes_.add(m);
              } else {
                attributeTypesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              com.aixohub.portfolio.model.proto.v1.PConfigurationSet m =
                  input.readMessage(
                      com.aixohub.portfolio.model.proto.v1.PConfigurationSet.parser(),
                      extensionRegistry);
              if (configurationSetsBuilder_ == null) {
                ensureConfigurationSetsIsMutable();
                configurationSets_.add(m);
              } else {
                configurationSetsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.aixohub.portfolio.model.proto.v1.PBookmark> bookmarks_ =
      java.util.Collections.emptyList();
    private void ensureBookmarksIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        bookmarks_ = new java.util.ArrayList<com.aixohub.portfolio.model.proto.v1.PBookmark>(bookmarks_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aixohub.portfolio.model.proto.v1.PBookmark, com.aixohub.portfolio.model.proto.v1.PBookmark.Builder, com.aixohub.portfolio.model.proto.v1.PBookmarkOrBuilder> bookmarksBuilder_;

    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public java.util.List<com.aixohub.portfolio.model.proto.v1.PBookmark> getBookmarksList() {
      if (bookmarksBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bookmarks_);
      } else {
        return bookmarksBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public int getBookmarksCount() {
      if (bookmarksBuilder_ == null) {
        return bookmarks_.size();
      } else {
        return bookmarksBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PBookmark getBookmarks(int index) {
      if (bookmarksBuilder_ == null) {
        return bookmarks_.get(index);
      } else {
        return bookmarksBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public Builder setBookmarks(
        int index, com.aixohub.portfolio.model.proto.v1.PBookmark value) {
      if (bookmarksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookmarksIsMutable();
        bookmarks_.set(index, value);
        onChanged();
      } else {
        bookmarksBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public Builder setBookmarks(
        int index, com.aixohub.portfolio.model.proto.v1.PBookmark.Builder builderForValue) {
      if (bookmarksBuilder_ == null) {
        ensureBookmarksIsMutable();
        bookmarks_.set(index, builderForValue.build());
        onChanged();
      } else {
        bookmarksBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public Builder addBookmarks(com.aixohub.portfolio.model.proto.v1.PBookmark value) {
      if (bookmarksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookmarksIsMutable();
        bookmarks_.add(value);
        onChanged();
      } else {
        bookmarksBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public Builder addBookmarks(
        int index, com.aixohub.portfolio.model.proto.v1.PBookmark value) {
      if (bookmarksBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookmarksIsMutable();
        bookmarks_.add(index, value);
        onChanged();
      } else {
        bookmarksBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public Builder addBookmarks(
        com.aixohub.portfolio.model.proto.v1.PBookmark.Builder builderForValue) {
      if (bookmarksBuilder_ == null) {
        ensureBookmarksIsMutable();
        bookmarks_.add(builderForValue.build());
        onChanged();
      } else {
        bookmarksBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public Builder addBookmarks(
        int index, com.aixohub.portfolio.model.proto.v1.PBookmark.Builder builderForValue) {
      if (bookmarksBuilder_ == null) {
        ensureBookmarksIsMutable();
        bookmarks_.add(index, builderForValue.build());
        onChanged();
      } else {
        bookmarksBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public Builder addAllBookmarks(
        java.lang.Iterable<? extends com.aixohub.portfolio.model.proto.v1.PBookmark> values) {
      if (bookmarksBuilder_ == null) {
        ensureBookmarksIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bookmarks_);
        onChanged();
      } else {
        bookmarksBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public Builder clearBookmarks() {
      if (bookmarksBuilder_ == null) {
        bookmarks_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bookmarksBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public Builder removeBookmarks(int index) {
      if (bookmarksBuilder_ == null) {
        ensureBookmarksIsMutable();
        bookmarks_.remove(index);
        onChanged();
      } else {
        bookmarksBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PBookmark.Builder getBookmarksBuilder(
        int index) {
      return getBookmarksFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PBookmarkOrBuilder getBookmarksOrBuilder(
        int index) {
      if (bookmarksBuilder_ == null) {
        return bookmarks_.get(index);  } else {
        return bookmarksBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PBookmarkOrBuilder> 
         getBookmarksOrBuilderList() {
      if (bookmarksBuilder_ != null) {
        return bookmarksBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bookmarks_);
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PBookmark.Builder addBookmarksBuilder() {
      return getBookmarksFieldBuilder().addBuilder(
          com.aixohub.portfolio.model.proto.v1.PBookmark.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PBookmark.Builder addBookmarksBuilder(
        int index) {
      return getBookmarksFieldBuilder().addBuilder(
          index, com.aixohub.portfolio.model.proto.v1.PBookmark.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
     */
    public java.util.List<com.aixohub.portfolio.model.proto.v1.PBookmark.Builder> 
         getBookmarksBuilderList() {
      return getBookmarksFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aixohub.portfolio.model.proto.v1.PBookmark, com.aixohub.portfolio.model.proto.v1.PBookmark.Builder, com.aixohub.portfolio.model.proto.v1.PBookmarkOrBuilder> 
        getBookmarksFieldBuilder() {
      if (bookmarksBuilder_ == null) {
        bookmarksBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.aixohub.portfolio.model.proto.v1.PBookmark, com.aixohub.portfolio.model.proto.v1.PBookmark.Builder, com.aixohub.portfolio.model.proto.v1.PBookmarkOrBuilder>(
                bookmarks_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        bookmarks_ = null;
      }
      return bookmarksBuilder_;
    }

    private java.util.List<com.aixohub.portfolio.model.proto.v1.PAttributeType> attributeTypes_ =
      java.util.Collections.emptyList();
    private void ensureAttributeTypesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        attributeTypes_ = new java.util.ArrayList<com.aixohub.portfolio.model.proto.v1.PAttributeType>(attributeTypes_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aixohub.portfolio.model.proto.v1.PAttributeType, com.aixohub.portfolio.model.proto.v1.PAttributeType.Builder, com.aixohub.portfolio.model.proto.v1.PAttributeTypeOrBuilder> attributeTypesBuilder_;

    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public java.util.List<com.aixohub.portfolio.model.proto.v1.PAttributeType> getAttributeTypesList() {
      if (attributeTypesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(attributeTypes_);
      } else {
        return attributeTypesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public int getAttributeTypesCount() {
      if (attributeTypesBuilder_ == null) {
        return attributeTypes_.size();
      } else {
        return attributeTypesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PAttributeType getAttributeTypes(int index) {
      if (attributeTypesBuilder_ == null) {
        return attributeTypes_.get(index);
      } else {
        return attributeTypesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public Builder setAttributeTypes(
        int index, com.aixohub.portfolio.model.proto.v1.PAttributeType value) {
      if (attributeTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeTypesIsMutable();
        attributeTypes_.set(index, value);
        onChanged();
      } else {
        attributeTypesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public Builder setAttributeTypes(
        int index, com.aixohub.portfolio.model.proto.v1.PAttributeType.Builder builderForValue) {
      if (attributeTypesBuilder_ == null) {
        ensureAttributeTypesIsMutable();
        attributeTypes_.set(index, builderForValue.build());
        onChanged();
      } else {
        attributeTypesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public Builder addAttributeTypes(com.aixohub.portfolio.model.proto.v1.PAttributeType value) {
      if (attributeTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeTypesIsMutable();
        attributeTypes_.add(value);
        onChanged();
      } else {
        attributeTypesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public Builder addAttributeTypes(
        int index, com.aixohub.portfolio.model.proto.v1.PAttributeType value) {
      if (attributeTypesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureAttributeTypesIsMutable();
        attributeTypes_.add(index, value);
        onChanged();
      } else {
        attributeTypesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public Builder addAttributeTypes(
        com.aixohub.portfolio.model.proto.v1.PAttributeType.Builder builderForValue) {
      if (attributeTypesBuilder_ == null) {
        ensureAttributeTypesIsMutable();
        attributeTypes_.add(builderForValue.build());
        onChanged();
      } else {
        attributeTypesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public Builder addAttributeTypes(
        int index, com.aixohub.portfolio.model.proto.v1.PAttributeType.Builder builderForValue) {
      if (attributeTypesBuilder_ == null) {
        ensureAttributeTypesIsMutable();
        attributeTypes_.add(index, builderForValue.build());
        onChanged();
      } else {
        attributeTypesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public Builder addAllAttributeTypes(
        java.lang.Iterable<? extends com.aixohub.portfolio.model.proto.v1.PAttributeType> values) {
      if (attributeTypesBuilder_ == null) {
        ensureAttributeTypesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attributeTypes_);
        onChanged();
      } else {
        attributeTypesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public Builder clearAttributeTypes() {
      if (attributeTypesBuilder_ == null) {
        attributeTypes_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        attributeTypesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public Builder removeAttributeTypes(int index) {
      if (attributeTypesBuilder_ == null) {
        ensureAttributeTypesIsMutable();
        attributeTypes_.remove(index);
        onChanged();
      } else {
        attributeTypesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PAttributeType.Builder getAttributeTypesBuilder(
        int index) {
      return getAttributeTypesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PAttributeTypeOrBuilder getAttributeTypesOrBuilder(
        int index) {
      if (attributeTypesBuilder_ == null) {
        return attributeTypes_.get(index);  } else {
        return attributeTypesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PAttributeTypeOrBuilder> 
         getAttributeTypesOrBuilderList() {
      if (attributeTypesBuilder_ != null) {
        return attributeTypesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(attributeTypes_);
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PAttributeType.Builder addAttributeTypesBuilder() {
      return getAttributeTypesFieldBuilder().addBuilder(
          com.aixohub.portfolio.model.proto.v1.PAttributeType.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PAttributeType.Builder addAttributeTypesBuilder(
        int index) {
      return getAttributeTypesFieldBuilder().addBuilder(
          index, com.aixohub.portfolio.model.proto.v1.PAttributeType.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
     */
    public java.util.List<com.aixohub.portfolio.model.proto.v1.PAttributeType.Builder> 
         getAttributeTypesBuilderList() {
      return getAttributeTypesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aixohub.portfolio.model.proto.v1.PAttributeType, com.aixohub.portfolio.model.proto.v1.PAttributeType.Builder, com.aixohub.portfolio.model.proto.v1.PAttributeTypeOrBuilder> 
        getAttributeTypesFieldBuilder() {
      if (attributeTypesBuilder_ == null) {
        attributeTypesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.aixohub.portfolio.model.proto.v1.PAttributeType, com.aixohub.portfolio.model.proto.v1.PAttributeType.Builder, com.aixohub.portfolio.model.proto.v1.PAttributeTypeOrBuilder>(
                attributeTypes_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        attributeTypes_ = null;
      }
      return attributeTypesBuilder_;
    }

    private java.util.List<com.aixohub.portfolio.model.proto.v1.PConfigurationSet> configurationSets_ =
      java.util.Collections.emptyList();
    private void ensureConfigurationSetsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        configurationSets_ = new java.util.ArrayList<com.aixohub.portfolio.model.proto.v1.PConfigurationSet>(configurationSets_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aixohub.portfolio.model.proto.v1.PConfigurationSet, com.aixohub.portfolio.model.proto.v1.PConfigurationSet.Builder, com.aixohub.portfolio.model.proto.v1.PConfigurationSetOrBuilder> configurationSetsBuilder_;

    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public java.util.List<com.aixohub.portfolio.model.proto.v1.PConfigurationSet> getConfigurationSetsList() {
      if (configurationSetsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(configurationSets_);
      } else {
        return configurationSetsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public int getConfigurationSetsCount() {
      if (configurationSetsBuilder_ == null) {
        return configurationSets_.size();
      } else {
        return configurationSetsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PConfigurationSet getConfigurationSets(int index) {
      if (configurationSetsBuilder_ == null) {
        return configurationSets_.get(index);
      } else {
        return configurationSetsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public Builder setConfigurationSets(
        int index, com.aixohub.portfolio.model.proto.v1.PConfigurationSet value) {
      if (configurationSetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigurationSetsIsMutable();
        configurationSets_.set(index, value);
        onChanged();
      } else {
        configurationSetsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public Builder setConfigurationSets(
        int index, com.aixohub.portfolio.model.proto.v1.PConfigurationSet.Builder builderForValue) {
      if (configurationSetsBuilder_ == null) {
        ensureConfigurationSetsIsMutable();
        configurationSets_.set(index, builderForValue.build());
        onChanged();
      } else {
        configurationSetsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public Builder addConfigurationSets(com.aixohub.portfolio.model.proto.v1.PConfigurationSet value) {
      if (configurationSetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigurationSetsIsMutable();
        configurationSets_.add(value);
        onChanged();
      } else {
        configurationSetsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public Builder addConfigurationSets(
        int index, com.aixohub.portfolio.model.proto.v1.PConfigurationSet value) {
      if (configurationSetsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureConfigurationSetsIsMutable();
        configurationSets_.add(index, value);
        onChanged();
      } else {
        configurationSetsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public Builder addConfigurationSets(
        com.aixohub.portfolio.model.proto.v1.PConfigurationSet.Builder builderForValue) {
      if (configurationSetsBuilder_ == null) {
        ensureConfigurationSetsIsMutable();
        configurationSets_.add(builderForValue.build());
        onChanged();
      } else {
        configurationSetsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public Builder addConfigurationSets(
        int index, com.aixohub.portfolio.model.proto.v1.PConfigurationSet.Builder builderForValue) {
      if (configurationSetsBuilder_ == null) {
        ensureConfigurationSetsIsMutable();
        configurationSets_.add(index, builderForValue.build());
        onChanged();
      } else {
        configurationSetsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public Builder addAllConfigurationSets(
        java.lang.Iterable<? extends com.aixohub.portfolio.model.proto.v1.PConfigurationSet> values) {
      if (configurationSetsBuilder_ == null) {
        ensureConfigurationSetsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, configurationSets_);
        onChanged();
      } else {
        configurationSetsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public Builder clearConfigurationSets() {
      if (configurationSetsBuilder_ == null) {
        configurationSets_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        configurationSetsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public Builder removeConfigurationSets(int index) {
      if (configurationSetsBuilder_ == null) {
        ensureConfigurationSetsIsMutable();
        configurationSets_.remove(index);
        onChanged();
      } else {
        configurationSetsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PConfigurationSet.Builder getConfigurationSetsBuilder(
        int index) {
      return getConfigurationSetsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PConfigurationSetOrBuilder getConfigurationSetsOrBuilder(
        int index) {
      if (configurationSetsBuilder_ == null) {
        return configurationSets_.get(index);  } else {
        return configurationSetsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PConfigurationSetOrBuilder> 
         getConfigurationSetsOrBuilderList() {
      if (configurationSetsBuilder_ != null) {
        return configurationSetsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(configurationSets_);
      }
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PConfigurationSet.Builder addConfigurationSetsBuilder() {
      return getConfigurationSetsFieldBuilder().addBuilder(
          com.aixohub.portfolio.model.proto.v1.PConfigurationSet.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public com.aixohub.portfolio.model.proto.v1.PConfigurationSet.Builder addConfigurationSetsBuilder(
        int index) {
      return getConfigurationSetsFieldBuilder().addBuilder(
          index, com.aixohub.portfolio.model.proto.v1.PConfigurationSet.getDefaultInstance());
    }
    /**
     * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
     */
    public java.util.List<com.aixohub.portfolio.model.proto.v1.PConfigurationSet.Builder> 
         getConfigurationSetsBuilderList() {
      return getConfigurationSetsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.aixohub.portfolio.model.proto.v1.PConfigurationSet, com.aixohub.portfolio.model.proto.v1.PConfigurationSet.Builder, com.aixohub.portfolio.model.proto.v1.PConfigurationSetOrBuilder> 
        getConfigurationSetsFieldBuilder() {
      if (configurationSetsBuilder_ == null) {
        configurationSetsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.aixohub.portfolio.model.proto.v1.PConfigurationSet, com.aixohub.portfolio.model.proto.v1.PConfigurationSet.Builder, com.aixohub.portfolio.model.proto.v1.PConfigurationSetOrBuilder>(
                configurationSets_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        configurationSets_ = null;
      }
      return configurationSetsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.aixohub.portfolio.PSettings)
  }

  // @@protoc_insertion_point(class_scope:com.aixohub.portfolio.PSettings)
  private static final com.aixohub.portfolio.model.proto.v1.PSettings DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.aixohub.portfolio.model.proto.v1.PSettings();
  }

  public static com.aixohub.portfolio.model.proto.v1.PSettings getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PSettings>
      PARSER = new com.google.protobuf.AbstractParser<PSettings>() {
    @java.lang.Override
    public PSettings parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PSettings> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PSettings> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.aixohub.portfolio.model.proto.v1.PSettings getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

