// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: client.proto

package com.aixohub.portfolio.model.proto.v1;

public interface PSettingsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.aixohub.portfolio.PSettings)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PBookmark> 
      getBookmarksList();
  /**
   * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PBookmark getBookmarks(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
   */
  int getBookmarksCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PBookmarkOrBuilder> 
      getBookmarksOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PBookmark bookmarks = 1;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PBookmarkOrBuilder getBookmarksOrBuilder(
      int index);

  /**
   * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PAttributeType> 
      getAttributeTypesList();
  /**
   * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PAttributeType getAttributeTypes(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
   */
  int getAttributeTypesCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PAttributeTypeOrBuilder> 
      getAttributeTypesOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PAttributeType attributeTypes = 2;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PAttributeTypeOrBuilder getAttributeTypesOrBuilder(
      int index);

  /**
   * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
   */
  java.util.List<com.aixohub.portfolio.model.proto.v1.PConfigurationSet> 
      getConfigurationSetsList();
  /**
   * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PConfigurationSet getConfigurationSets(int index);
  /**
   * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
   */
  int getConfigurationSetsCount();
  /**
   * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
   */
  java.util.List<? extends com.aixohub.portfolio.model.proto.v1.PConfigurationSetOrBuilder> 
      getConfigurationSetsOrBuilderList();
  /**
   * <code>repeated .com.aixohub.portfolio.PConfigurationSet configurationSets = 3;</code>
   */
  com.aixohub.portfolio.model.proto.v1.PConfigurationSetOrBuilder getConfigurationSetsOrBuilder(
      int index);
}
